### PR TITLE
Print serial number of CM0+ target

### PR DESCRIPTION
**Pull request by ooxi**
By printing the serial number of the target acted upon enables a lot of use cases like statistical analysis and tracability. The serial number is read from the devices memory using SWD.

Successfully tested on samd21 hardware as well as verified using datasheet of the following targets:

* [samd09](https://github.com/ataradov/edbg/files/4031781/atmel-42414-sam-d09_datasheet.pdf)
* [samd10](https://github.com/ataradov/edbg/files/4031780/atmel-42242-sam-d10_datasheet.pdf)
* [samd11](https://github.com/ataradov/edbg/files/4031779/atmel-42363-sam-d11_datasheet.pdf)
* [samd20](https://github.com/ataradov/edbg/files/4031778/60001504B.samd20.pdf)
* [samd21](https://github.com/ataradov/edbg/files/4031777/Atmel-42181-SAM-D21_Datasheet.pdf)
* [samc21](https://github.com/ataradov/edbg/files/4031776/Atmel-42365-SAMC21_Datasheet-894213.pdf)
* [saml21](https://github.com/ataradov/edbg/files/4031775/60001477A.saml21.pdf)
* [saml22](https://github.com/ataradov/edbg/files/4031774/60001465A.saml22.pdf)
* [samr21](https://github.com/ataradov/edbg/files/4031773/sam-r21_datasheet.pdf)
* [samr30](https://github.com/ataradov/edbg/files/4031772/70005303b-1108106.samr30.pdf)
* [samda1](https://github.com/ataradov/edbg/files/4031771/40001895A.samda1.pdf)

However the targets samr34 as well as samr35 do not seem to support serial number extraction. I wanted to keep the pull request as small as possible, but I can implement a device discrimation if you want in order to not print wrong serial numbers for unsupported devices.

For my usecase it would be very helpful to be able to read the serial number into a file, however I did not find information about a unique device identification for other targets then CM0+.

Sample output:

```
Debugger: ATMEL EDBG CMSIS-DAP ATML2130021800020377 03.22.01B3 (S)
Clock frequency: 16.0 MHz
Target: SAM D21J18A (Rev D)
Serial number: 41eebbfe 514d3559 34202020 ff0f2a24
Programming.............................................................................. done.
Verification.............................................................................. done.
```

### CODE REVIEW

**Comment by ataradov** [comment]
I will not merge this. This has nothing to do with programming the part. And by keeping the code small and simple you are able to take it and modify for your needs.

If you need to have serial numbers, it is fine, but there is no need for everyone to have it.

**Comment by ooxi** [comment]
Well I can see you reasoning, however we also print the target `DSU_DID` which is not strictly required for programming either.

If you do not reconsider (and you are under no obligation to do so), I will carry this patch in a small fork :-)

**Comment by ataradov** [comment]
We only print it when the target is not known. DSU_DID is required for ongoing maintenance. It is less relevant not that revision is masked out, but previously situation when a part is not recognized because of a different revision number were common. Printing DSU_DID in this case is more user friendly than just printing "unknown part". We also need to read it anyway, since it is used as part of the part detection method.

**Comment by ooxi** [comment]
For future reference: patch will be carried in [edbg-serial-number](https://github.com/ooxi/edbg-serial-number/).

**Pull request closed without merging**
