### PR TITLE
Woody

### PR DESCRIPTION
**Pull request by mattwood2000**
Added SAMR30 to cm0p and and M7 GPNVM bit read/write support.

### CODE REVIEW

**Comment by ataradov** [comment]
Hi Matt,

This user interface is way too specific for V7x devices. I wanted to have a more universal interface that will be applicable to other devices as well. 

The fuse thing has been waiting for a long time, so I guess it is time to implement it fully.

I will think of a better UI for this in the next couple days.

**Comment by mattwood2000** [comment]
Hi Alex,

I thought this was the most generic way to provide a user interface.  As you know, the M3 and M4 devices have different GPNVM configurations than the M7.  The M0+ families have even more complex fuse bit configurations.  So, my intention was to force the user to be responsible for knowing the GPNVM bit mask(s) to avoid having the tool keep track of every single device/fuse configuration.

I just happened to start on the M7 family as I had specific production testing needs to handle, but I was going to move this over the M3/4 devices as well.

However, if you have a more intuitive method, I look forward to it!

Thanks, Matt.

**Comment by ataradov** [comment]
I combined all fuse operations into a single command. For now it looks something like this:

    Fuse operations format: <actions>,<index/range>,<value>
      <actions>     - any combination of 'r' (read), 'w' (write), 'v' (verify)
      <index/range> - index of the fuse, or a range of fuses (limits separated by ':')
                      specify empty range to read all available fuses
                      specify '*' to read and write values from a file
      <value>       - fuses value or file name for write and verify operations
                      immediate values must be 32 bits or less

    Exact fuse bits locations and values are target-dependent.

    Examples:
      -F w,1,1                -- set fuse bit 1\n
      -F w,8:7,0              -- clear fuse bits 8 and 7
      -F v,31:0,0x12345678    -- verify that fuse bits 31-0 are equal to 0x12345678
      -F wv,5,1               -- set and verify fuse bit 5
      -F r,,                  -- read all fuses
      -F wv,*,fuses.bin       -- write and verify all fuses from a file

I've implemented a parser for all this, I just need to add the actual code. I'll try to do that later today.

**Comment by mattwood2000** [comment]
Hi Alex,

that looks good and is certainly generic enough to implement across the
chip specific differences.

Thanks for the work on this, it is a great tool.

Matt.

**Comment by ataradov** [comment]
I've added fuse support. "edbg -h fuse" will print a fuse-specific help. This was tested only on D21 and V71, but should work for other devices as well.

I also merged new parts.

I removed automatic setting of GPNVM1 after programming, since it was a hack due to lack of fuse support.

**Pull request closed without merging**
